### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.EnvironmentSpecs
    name: EnvironmentSpecs
    fullName: EnvironmentSpecs
    children:
      - Api.Js.SxcJs.EnvironmentSpecs.api
      - Api.Js.SxcJs.EnvironmentSpecs.appApi
      - Api.Js.SxcJs.EnvironmentSpecs.page
      - Api.Js.SxcJs.EnvironmentSpecs.platform
      - Api.Js.SxcJs.EnvironmentSpecs.root
      - Api.Js.SxcJs.EnvironmentSpecs.rvt
      - Api.Js.SxcJs.EnvironmentSpecs.rvtHeader
    langs:
      - typeScript
    type: interface
    summary: >-
      A context information for the current page, helping the JS talk with the
      backend
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.api
    name: api
    fullName: api
    children: []
    langs:
      - typeScript
    type: property
    summary: >-
      Optional API key - optional if set from external, because it's auto
      derived from root
    syntax:
      content: 'api: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.appApi
    name: appApi
    fullName: appApi
    children: []
    langs:
      - typeScript
    type: property
    summary: >-
      Optional App API Root - required because in Oqtane we'll have a different
      root for appAPIs
    syntax:
      content: 'appApi: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.page
    name: page
    fullName: page
    children: []
    langs:
      - typeScript
    type: property
    summary: Page ID
    syntax:
      content: 'page: number'
      return:
        type:
          - number
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.platform
    name: platform
    fullName: platform
    children: []
    langs:
      - typeScript
    type: property
    summary: The platform code like 'dnn' or 'oqt'
    syntax:
      content: 'platform: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.root
    name: root
    fullName: root
    children: []
    langs:
      - typeScript
    type: property
    summary: Portal root path - used for various things incl. the API root
    syntax:
      content: 'root: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.rvt
    name: rvt
    fullName: rvt
    children: []
    langs:
      - typeScript
    type: property
    summary: Request verification token value
    syntax:
      content: 'rvt: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.EnvironmentSpecs.rvtHeader
    name: rvtHeader
    fullName: rvtHeader
    children: []
    langs:
      - typeScript
    type: property
    summary: Request verification token header name
    syntax:
      content: 'rvtHeader: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
