### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.QuickEditConfig
    name: QuickEditConfig
    fullName: QuickEditConfig
    children:
      - Api.Js.SxcJs.QuickEditConfig.buttons
      - Api.Js.SxcJs.QuickEditConfig.enable
    langs:
      - typeScript
    type: class
    summary: >-
      Quick Edit Configuration which has an `enable` and specific button
      configurations
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfig.buttons
    name: buttons
    fullName: buttons
    children: []
    langs:
      - typeScript
    type: property
    summary: Optional detailed configuration of the buttons.
    optional: true
    syntax:
      content: 'buttons?: QuickEditConfigButtons'
      return:
        type:
          - Api.Js.SxcJs.QuickEditConfigButtons
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfig.enable
    name: enable
    fullName: enable
    children: []
    langs:
      - typeScript
    type: property
    summary: Determine whether this section is enabled.
    optional: true
    syntax:
      content: 'enable?: boolean | "auto"'
      return:
        type:
          - boolean | "auto"
        description: ''
    package: Api.Js.SxcJs
references:
  - uid: Api.Js.SxcJs.QuickEditConfigButtons
    name: QuickEditConfigButtons
    spec.typeScript:
      - name: QuickEditConfigButtons
        fullName: QuickEditConfigButtons
        uid: Api.Js.SxcJs.QuickEditConfigButtons
