### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.QuickEditConfigRoot
    name: QuickEditConfigRoot
    fullName: QuickEditConfigRoot
    children:
      - Api.Js.SxcJs.QuickEditConfigRoot.buttons
      - Api.Js.SxcJs.QuickEditConfigRoot.enable
      - Api.Js.SxcJs.QuickEditConfigRoot.innerBlocks
      - Api.Js.SxcJs.QuickEditConfigRoot.modules
    langs:
      - typeScript
    type: class
    summary: >-
      Quick Edit - Full configuration at root, with `enable` and rules for
      `modules` and `innerBlocks`
    extends:
      name: Api.Js.SxcJs.QuickEditConfig
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigRoot.buttons
    name: buttons
    fullName: buttons
    children: []
    langs:
      - typeScript
    type: property
    summary: |-
      The buttons configuration on the root.
      Will be used for the `modules` and `innerBlocks` if not specified there.
      Note that if not specified, will always default to true for all buttons.
    optional: true
    syntax:
      content: 'buttons?: QuickEditConfigButtons'
      return:
        type:
          - Api.Js.SxcJs.QuickEditConfigButtons
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigRoot.enable
    name: enable
    fullName: enable
    children: []
    langs:
      - typeScript
    type: property
    summary: Determine whether this section is enabled.
    optional: true
    syntax:
      content: 'enable?: boolean | "auto"'
      return:
        type:
          - boolean | "auto"
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigRoot.innerBlocks
    name: innerBlocks
    fullName: innerBlocks
    children: []
    langs:
      - typeScript
    type: property
    summary: Optional configuration for the Inner Content Blocks.
    optional: true
    syntax:
      content: 'innerBlocks?: QuickEditConfig'
      return:
        type:
          - Api.Js.SxcJs.QuickEditConfig
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigRoot.modules
    name: modules
    fullName: modules
    children: []
    langs:
      - typeScript
    type: property
    summary: Optional configuration for the Modules.
    optional: true
    syntax:
      content: 'modules?: QuickEditConfig'
      return:
        type:
          - Api.Js.SxcJs.QuickEditConfig
        description: ''
    package: Api.Js.SxcJs
references:
  - uid: Api.Js.SxcJs.QuickEditConfig
    name: QuickEditConfig
    spec.typeScript:
      - name: QuickEditConfig
        fullName: QuickEditConfig
        uid: Api.Js.SxcJs.QuickEditConfig
  - uid: Api.Js.SxcJs.QuickEditConfigButtons
    name: QuickEditConfigButtons
    spec.typeScript:
      - name: QuickEditConfigButtons
        fullName: QuickEditConfigButtons
        uid: Api.Js.SxcJs.QuickEditConfigButtons
