### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.QuickEditConfigButtons
    name: QuickEditConfigButtons
    fullName: QuickEditConfigButtons
    children:
      - Api.Js.SxcJs.QuickEditConfigButtons.addApp
      - Api.Js.SxcJs.QuickEditConfigButtons.addContent
      - Api.Js.SxcJs.QuickEditConfigButtons.delete
      - Api.Js.SxcJs.QuickEditConfigButtons.move
      - Api.Js.SxcJs.QuickEditConfigButtons.paste
      - Api.Js.SxcJs.QuickEditConfigButtons.select
    langs:
      - typeScript
    type: class
    summary: Buttons on a quick-edit toolbar
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.addApp
    name: addApp
    fullName: addApp
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button to "add App"
    optional: true
    syntax:
      content: 'addApp?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.addContent
    name: addContent
    fullName: addContent
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button to "Add Content"
    optional: true
    syntax:
      content: 'addContent?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.delete
    name: delete
    fullName: delete
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button "Delete"
    optional: true
    syntax:
      content: 'delete?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.move
    name: move
    fullName: move
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button "Move"
    optional: true
    syntax:
      content: 'move?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.paste
    name: paste
    fullName: paste
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button "Paste"
    optional: true
    syntax:
      content: 'paste?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.QuickEditConfigButtons.select
    name: select
    fullName: select
    children: []
    langs:
      - typeScript
    type: property
    summary: Enable the button "Select"
    optional: true
    syntax:
      content: 'select?: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
