### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment
    name: SxcGlobalEnvironment
    fullName: SxcGlobalEnvironment
    children:
      - Api.Js.SxcJs.SxcGlobalEnvironment.api
      - Api.Js.SxcJs.SxcGlobalEnvironment.load
      - Api.Js.SxcJs.SxcGlobalEnvironment.page
      - Api.Js.SxcJs.SxcGlobalEnvironment.platform
      - Api.Js.SxcJs.SxcGlobalEnvironment.ready
      - Api.Js.SxcJs.SxcGlobalEnvironment.rvt
      - Api.Js.SxcJs.SxcGlobalEnvironment.rvtHeader
      - Api.Js.SxcJs.SxcGlobalEnvironment.source
    langs:
      - typeScript
    type: class
    summary: >-
      Provides environment information to $2sxc - usually page-id, api-root and
      stuff like that
    extends:
      name: Api.Js.SxcJs.HasLog
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.api
    name: api()
    children: []
    type: method
    langs:
      - typeScript
    summary: The API endpoint url from the environment
    syntax:
      content: function api()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.load
    name: 'load(EnvironmentSpecs, string)'
    children: []
    type: method
    langs:
      - typeScript
    summary: >-
      Manually load a new EnvironmentSpecs in cases where the page cannot
      provide them.

      This is only used in scenarios outside of Dnn / Oqtane, you will usually
      not need this.
    syntax:
      content: 'function load(envSpecs: EnvironmentSpecs, source?: string)'
      parameters:
        - id: envSpecs
          type:
            - Api.Js.SxcJs.EnvironmentSpecs
          description: new info to load
        - id: source
          type:
            - string
          description: |
            _optional_ name where the data came from
          optional: true
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.page
    name: page()
    children: []
    type: method
    langs:
      - typeScript
    summary: The current page ID - often needed in API calls
    syntax:
      content: function page()
      parameters: []
      return:
        type:
          - number
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.platform
    name: platform()
    children: []
    type: method
    langs:
      - typeScript
    summary: >-
      The platform code like 'oqt' or 'dnn' in case the JS needs to know the
      difference
    syntax:
      content: function platform()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.ready
    name: ready
    fullName: ready
    children: []
    langs:
      - typeScript
    type: property
    summary: Flag to determine if the environment information is available.
    syntax:
      content: 'ready: boolean'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.rvt
    name: rvt()
    children: []
    type: method
    langs:
      - typeScript
    summary: The request-verification token for internal WebAPI calls
    syntax:
      content: function rvt()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.rvtHeader
    name: rvtHeader()
    children: []
    type: method
    langs:
      - typeScript
    summary: The request verification token header name for internal WebAPI calls
    syntax:
      content: function rvtHeader()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.SxcGlobalEnvironment.source
    name: source
    fullName: source
    children: []
    langs:
      - typeScript
    type: property
    summary: Where the environment information came from.
    syntax:
      content: 'source: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
references:
  - uid: Api.Js.SxcJs.HasLog
    name: HasLog
    spec.typeScript:
      - name: HasLog
        fullName: HasLog
        uid: Api.Js.SxcJs.HasLog
  - uid: Api.Js.SxcJs.EnvironmentSpecs
    name: EnvironmentSpecs
    spec.typeScript:
      - name: EnvironmentSpecs
        fullName: EnvironmentSpecs
        uid: Api.Js.SxcJs.EnvironmentSpecs
