### YamlMime:UniversalReference
items:
  - uid: Api.Js.SxcJs.ZzzAjaxSettingsDeprecated
    name: ZzzAjaxSettingsDeprecated
    fullName: ZzzAjaxSettingsDeprecated
    children:
      - Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.action
      - Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.controller
      - Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.params
    langs:
      - typeScript
    type: interface
    summary: |-
      Deprecated parameters for old jQuery AJAX calls.
      Shouldn't be used any more.
    package: Api.Js.SxcJs
    deprecated:
      content: ''
  - uid: Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.action
    name: action
    fullName: action
    children: []
    langs:
      - typeScript
    type: property
    summary: 'action name, for controller/action calls'
    optional: true
    syntax:
      content: 'action?: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.controller
    name: controller
    fullName: controller
    children: []
    langs:
      - typeScript
    type: property
    summary: 'Controller name, for controller/action calls'
    optional: true
    syntax:
      content: 'controller?: string'
      return:
        type:
          - string
        description: ''
    package: Api.Js.SxcJs
  - uid: Api.Js.SxcJs.ZzzAjaxSettingsDeprecated.params
    name: params
    fullName: params
    children: []
    langs:
      - typeScript
    type: property
    summary: The params to be used in the url for the request
    optional: true
    syntax:
      content: 'params?: any'
      return:
        type:
          - any
        description: ''
    package: Api.Js.SxcJs
